# Generated by Django 2.2.5 on 2020-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200511_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='学习人数',
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='课程数',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
